### ISSUE TITLE
HTML pipeline should use downloader

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-index-pipelines#138]
As `helix-pipeline` is in its dependencies, it can use [Downloader.js](https://github.com/adobe/helix-pipeline/blob/master/src/utils/Downloader.js)

**Comment by tripodsan** [comment]
> As `helix-pipeline` is in its dependencies, it can use [Downloader.js](https://github.com/adobe/helix-pipeline/blob/master/src/utils/Downloader.js)

the downloader is provided via `action.downloader`:  see https://github.com/adobe/helix-pipeline/blob/master/src/html/fetch-fstab.js
