### ISSUE TITLE
convert to normal service action

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-pipelines#298]
AFAICR, index-pipelines is a pipeline action, because it originally was integrated in helix-pages.
since the action requests the HTML from a different site that it is run, there is no immediate benefit of (ab)using a pipeline action for it.

### Suggestion

Create a service action that implements the HTML indexing like it is done here. Currently, the other indexings (markdown, image) are not used. they could be added later.

Converting would have the benefit that it can be managed and deployed like all other actions and it is easier to develop further changes and create unit tests (I think).

**Comment by tripodsan** [comment]
@trieloff @dominique-pfister WDYT?

**Comment by dominique-pfister** [comment]
I agree: I just recently thought that the other actions were not used, and that the way the index-pipelines is currently deployed - each new version creates a new package name - incurs an extra step to set up coralogix logging support.

**Comment by trieloff** [comment]
Ok
