### ISSUE TITLE
make `el` implicit again

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-pipelines#45]
it would be nice, if the `el` would be implicitly added to the `context`, so that it doesn't need to specified in the yaml.

**Comment by tripodsan** [comment]
I think we close this for now.

**Comment by dominique-pfister** [comment]
With the addition of response headers, this would become more difficult, e.g. with the following `value` definition
```
parseTimestamp(headers['last-modified'], 'ddd, DD MMM YYYY hh:mm:ss GMT')
```
we'd need to differentiate between functions invoked implicitly on `el`, and functions invoked on the arguments given instead.
