### ISSUE TITLE
Create status page and new relic config

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-pipelines#6]
@rofe this is a bit a special action that is kind of deployed like normal helix-projects.
so we don't have the status check.

**Comment by rofe** [comment]
Sure, we can set it up manually for now, but what speaks against using the standard health check from `helix-status`? In any case, we would first need https://github.com/adobe/helix-continuous/issues/50.

**Comment by rofe** [comment]
https://github.com/adobe/helix-continuous/issues/50 is fixed. See https://circleci.com/orbs/registry/orb/adobe/helix-post-deploy for documentation.

**Comment by trieloff** [comment]
We probably need to adjust Helix-status to work in a Pre.js for that to work.

**Comment by tripodsan** [comment]
hmm... I'd rather have a cgi-bin:

`cgi-bin/status.js`
```
module.exports = require('@adobe/helix-status').report;
```

and then configure the url to:

```
https://adobeioruntime/web/helix-index/helix-index-pipelines/cgi-bin-status@latest
```

**Comment by trieloff** [comment]
That would work, too - but cgi-bin is deployed as a separate action, so the status won't detect broken pipelines or bad dependencies.

**Comment by tripodsan** [comment]
hmm, it could have all the other actions as backend-checks...

I think we don't want to have to setup several check URLs for 1 component? @rofe, would that be possible, to give the new relic script an array of URLs to check?

**Comment by tripodsan** [comment]
I would add the status check directly to helix-pipeline.... so that any deployed script action can be checked.

**Comment by trieloff** [comment]
Adding it to all pipelines is a good idea, but I'd make it an explicit step instead to hiding it in the OpenWhisk wrapper.

**Comment by tripodsan** [comment]
I would like to add it to all pipelines. if you add it as step, custom pipelines might lack it.
also, it should probably be the first step and _stop_ the pipeline after that.
also, it should only be invokable via adobeioruntime.

**Comment by rofe** [comment]
> @rofe, would that be possible

Sure, we can do what we want in the monitor script.

**Comment by trieloff** [comment]
Not that I feel strongly about it, but status being a proper step seems advantageous because it keeps the uniformity of the architecture. Before we know it, we will have regular pipeline plugins and special plugins and that will make things harder to understand.

**Comment by tripodsan** [comment]
I see your point. we can try with the extra step and see how it works out. it also allows the user to choose on how to enable it. is it already possible for a step to early terminate the pipeline? maybe with a error-handler-bracket :-)

**Comment by tripodsan** [comment]
I think this should be covered with #299

**Comment by rofe** [comment]
I think we could remove the `incubator` flag now...
